### ISSUE TITLE
Convert dimse dicom dataset to json

### ISSUE THREAD

**Issue by lam0620** [OHIF/dicom-dimse#5]
Hi,

I'm searching a solution to convert response dimse dicom dataset to json format follow DICOM Json Model (http://dicom.nema.org/dicom/2013/output/chtml/part18/sect_F.4.html)

I appreciate so much if anybody help

**Comment by pieper** [comment]
Hi - 

We moved all of that into a dedicated library for parsing/encoding/manipulating dicom instances with javascript:

https://github.com/dcmjs-org/dcmjs

Have a look at the examples and let us know if you have any questions.  It's work-in-progress but already feature complete for several use cases.

Note we also added similar features to pydicom (also still considered alpha but mostly working) https://github.com/pydicom/pydicom/pull/862

**Comment by lam0620** [comment]
Hi @pieper 

Thank you so much. Let me try!
